name: Validations

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  validations:
    name: Validations
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Type Check
      - name: Run Type Check
        run: yarn run tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [validations]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Build
      - name: Run Build
        run: yarn run build

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: lib

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [validations, build]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "22.x"

      # Download Artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: lib
          path: lib

      # Publish
      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
