name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: "22.x"

      # Install Dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      # Run Build
      - name: Run Build
        run: yarn run build

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: lib

      # Publish
      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
